"""empty message

Revision ID: fbe7abcb9826
Revises: 3eb7c5b4cf4a
Create Date: 2022-06-01 23:11:43.234432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbe7abcb9826'
down_revision = '3eb7c5b4cf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=800), nullable=True))
    op.add_column('artist', sa.Column('Created_at', sa.DateTime(), nullable=True))
    op.alter_column('venue', 'Created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'Created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('artist', 'Created_at')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
